# Problem 44
# Pentagonal numbers are generated by the formula,  Pn = n(3n-1)/2. The first ten pentagonal
# numbers are: 1,5,12,22,35,51,70,92,117,145,..
# It can be seen that P4+P7 = 22+70 = 92 = P8. However, their difference, 70-22=48
# is not pentagonal.
## Find the pair of pentagonal numbers, Pj and Pk for which their sum and difference
# are pentagonal and D = |Pk-Pj| is minimised; what is the value of D?
import math


def is_pentagonal(x):
    if x <= 0:
        return False
    s = math.isqrt(1 + 24*x)
    return s * s == 1 + 24*x and (1 + s) % 6 == 0


def sol():
    for j in range(1, 5000):
        Pj = j * (3 * j - 1) // 2
        for k in range(j + 1, 5000):
            Pk = k * (3 * k - 1) // 2
            if is_pentagonal(Pk - Pj) and is_pentagonal(Pk + Pj):
                return Pk - Pj
    return 0


if __name__ == "__main__":
    print(sol())