# Problem 45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle      Tn = n(n + 1)/2  1,3,6,10,15,...
# Pentagonal	Pn = n(3n - 1)/2 1,5,12,22,35,...
# Hexagonal     Hn = n(2n - 1)   1,6,15,28,45,..
#
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
import math


def is_pentagonal(x):
    k = (1 + math.sqrt(1 + 24*x)) / 6
    return abs(k - round(k)) < 1e-10


def hexagonal(m):
    return m * (2*m - 1)


def sol():
    # every hexagonal number is also triangle number, so we need only check if is hexagonal and pentagonal
    # starting index (m) just above the one giving 40755
    m = int((1 + math.sqrt(1 + 8*40755)) / 4)
    while True:
        m += 1
        val = hexagonal(m)
        if is_pentagonal(val):
            return m, val


if __name__ == "__main__":
    print(sol())
