# Problem 049
# The arithmetic sequence, 1487,4817,8147, in which each of the terms increases by 3300,
# is unusual in two ways: (i) each of the three terms are prime, and,
# (ii) each of the 4-digit numbers are permutations of one another.
#
# There are no arithmetic sequences made up of three 1-,2-, or 3-digit primes, exhibiting this property,
# but there is one other 4-digit increasing sequence.
# What 12-digit number do you form by concatenating the three terms in this sequence?
from PE_utils import Primes
from PE_utils.math_utils import MathUtils

@MathUtils.timeit
def find_arithmetic_sequence(primes):
    for i in range(len(primes)):
        for j in range(i+1, len(primes)):
            number = 2*primes[j] - primes[i]
            if number in primes and set(str(primes[i])) == set(str(primes[j])) == set(str(number)):
                return str(primes[i]) + str(primes[j]) + str(number)
    return None


# faster version.. generated by ChatGPT
@MathUtils.timeit
def find_arithmetic_sequence2(primes):
    prime_set = set(primes)
    for i in range(len(primes)):
        si = set(str(primes[i]))
        for j in range(i + 1, len(primes)):
            sj = set(str(primes[j]))
            if si != sj:
                continue
            number = 2 * primes[j] - primes[i]
            if number in prime_set and set(str(number)) == si:
                return f"{primes[i]}{primes[j]}{number}"
    return None


if __name__ == "__main__":
    p = Primes(10000)
    selected_primes = p.primes_in_range(1488, 10000)
    print(find_arithmetic_sequence(selected_primes))
    print(find_arithmetic_sequence2(selected_primes))
